apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app
resources:
  - canary.yaml
  - configmap.yaml
  - deployment.yaml
  - hpa.yaml
  - metrics.yaml
  - namespace.yaml
  - pdb.yaml
labels:
  - pairs:
      app.kubernetes.io/name: demo-app
    includeTemplates: true
    includeSelectors: true 
  - pairs:
      app.kubernetes.io/managed-by: flux
    includeTemplates: true
